import { StandCoordsType } from "@/types/stand-coords";

export const standCoords: StandCoordsType = {
  stand1: { coords: "623,889,677,943" },
  stand2: { coords: "623,947,676,998" },
  stand3: { coords: "627,1048,683,1100" },
  stand4: { coords: "626,1105,682,1157" },
  stand5: { coords: "421,885,477,957" },
  stand6: { coords: "421,960,478,1030" },
  stand7: { coords: "421,1044,477,1117" },
  stand8: { coords: "421,1119,479,1194" },
  stand9: { coords: "491,1355,574,1405" },
  stand10: { coords: "405,1354,489,1407" },
  stand11: { coords: "756,1445,839,1497" },
  stand12: { coords: "847,1445,932,1499" },
  stand13: { coords: "943,1447,1025,1498" },
  stand14: { coords: "1111,1447,1196,1497" },
  stand15: { coords: "1204,1446,1284,1499" },
  stand16: { coords: "1290,1445,1373,1498" },
  stand17: { coords: "1391,1388,1452,1447" },
  stand18: { coords: "1392,1328,1448,1387" },
  stand19: { coords: "1389,1264,1447,1330" },
  stand20: { coords: "1392,1203,1450,1265" },
  stand21: { coords: "1391,1142,1451,1203" },
  stand22: { coords: "1391,1081,1447,1141" },
  stand23: { coords: "1393,1021,1452,1080" },
  stand24: { coords: "1392,958,1448,1019" },
  stand25: { coords: "1392,896,1451,956" },
  stand26: { coords: "1392,830,1450,897" },
};

//generated by http://labs.d-s-b.jp/ImagemapGenerator/
// <img src="598f07b33cb6de66-1_pages-to-jpg-0001.jpg" usemap="#ImageMap" alt="" />
// <map name="ImageMap">
//   <area shape="rect" coords="622,889,679,946" href="#" alt="stand1" />
//   <area shape="rect" coords="623,947,678,1001" href="#" alt="stand2" />
//   <area shape="rect" coords="626,1050,686,1102" href="#" alt="stand3" />
//   <area shape="rect" coords="626,1105,682,1157" href="#" alt="stand4" />
//   <area shape="rect" coords="421,885,477,957" href="#" alt="stand5" />
//   <area shape="rect" coords="421,960,478,1030" href="#" alt="stand6" />
//   <area shape="rect" coords="421,1044,477,1117" href="#" alt="stand7" />
//   <area shape="rect" coords="421,1119,479,1194" href="#" alt="stand8" />
//   <area shape="rect" coords="491,1355,574,1405" href="#" alt="stand9" />
//   <area shape="rect" coords="405,1354,489,1407" href="#" alt="stand10" />
//   <area shape="rect" coords="756,1445,839,1497" href="#" alt="stand11" />
//   <area shape="rect" coords="847,1445,932,1499" href="#" alt="stand12" />
//   <area shape="rect" coords="943,1447,1025,1498" href="#" alt="stand13" />
//   <area shape="rect" coords="1111,1447,1196,1497" href="#" alt="stand14" />
//   <area shape="rect" coords="1204,1446,1284,1499" href="#" alt="stand15" />
//   <area shape="rect" coords="1290,1445,1373,1498" href="#" alt="stand16" />
//   <area shape="rect" coords="1391,1388,1452,1447" href="#" alt="stand17" />
//   <area shape="rect" coords="1392,1328,1448,1387" href="#" alt="stand18" />
//   <area shape="rect" coords="1389,1264,1447,1330" href="#" alt="stand19" />
//   <area shape="rect" coords="1392,1203,1450,1265" href="#" alt="stand20" />
//   <area shape="rect" coords="1391,1142,1451,1203" href="#" alt="stand21" />
//   <area shape="rect" coords="1391,1081,1447,1141" href="#" alt="stand22" />
//   <area shape="rect" coords="1393,1021,1452,1080" href="#" alt="stand23" />
//   <area shape="rect" coords="1392,958,1448,1019" href="#" alt="stand24" />
//   <area shape="rect" coords="1392,896,1451,956" href="#" alt="stand25" />
//   <area shape="rect" coords="1392,830,1450,897" href="#" alt="stand26" />
// </map>
