name: Test

on:
  pull_request:
    paths:
      - "**.py"
  push:
    branches:
      - main
    paths:
      - "**.py"

jobs:
  pytest:
    strategy:
      matrix:
        python-version: ["3.10"]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    name: Pytest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Setup python version ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: SSH Setting
        env:
          AKARI_REPO_SSH_PRIVATE_KEY: ${{ secrets.AKARI_REPO_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p /home/runner/.ssh/
          echo -e ${AKARI_REPO_SSH_PRIVATE_KEY} | base64 -d > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Install project
        run: poetry install
      - name: Format
        run: make fmt
      - uses: AustinScola/mypy-cache-github-action@v1
        name: Cache mypy cache
      - name: Lint
        run: make lint
      - name: Run Test
        run: make test
